# Copied from https://github.com/actions/hello-world-docker-action/
name: checklicense
description: Check License
author: awalterschulze

# Define your inputs here.
inputs:
  path:
    description: Path
  ignores:
    description: Ignores

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_IGNORES: ${{ inputs.ignores }}