name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: gopath/github.com/awalterschulze/checklicense
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
    - name: Check license
      run: |
        cd gopath/github.com/awalterschulze/checklicense
        go install github.com/awalterschulze/checklicense@latest
        checklicense .